# Use postgres/example user/password credentials
version: '3.1'

services:

  postgresdb:
    image: postgres:12
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: recommendation
      POSTGRES_USER: postgres
    ports:
    - 5432:5432

  custom-mongo:
    build: MongoDB/.
    image: custom-mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
    - 27017:27017
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: recommendation
      RABBITMQ_DEFAULT_PASS: recommendation

    #  for test only
  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongod-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: 10.200.200.90
    depends_on:
      - 'custom-mongo'